In [110]:
import numpy as np

In [111]:
a = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [112]:
#getting specific row and column value (2nd row and 4th column which is 12 --- Index starts from zero)
a[0][3]

4

In [113]:
# to get a specific row
a[1,:]

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [114]:
# to get a specific column
a[:,2]

array([ 3, 11])

In [115]:
#2nd row and 2nd and 3rd column values
a[1,1:3]

array([10, 11])

In [116]:
# 1st row ; start at 2nd element and go upto 7th element with step size of 2
a[0,1:6:2]

array([2, 4, 6])

In [117]:
#Changing value of last row and last column to 18
a[1,7] = 18
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 18]])

In [118]:
b=np.array([[1,3],[2,3],[3,5],[8,9]])
b

array([[1, 3],
       [2, 3],
       [3, 5],
       [8, 9]])

In [119]:
#with normal lists
a=[1,2,3]
b=[1,2,3]
ans = (a*b)
print(ans)

TypeError: can't multiply sequence by non-int of type 'list'

In [121]:
#with Numpy array
a=np.array([1,2,3])
b=np.array([1,2,3])
ans = a*b
print(ans)

[1 4 9]


In [129]:
#initilize array with zeroes
a=np.zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [131]:
b= np.zeros([3,3,3])
print(b)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [135]:
np.ones([3,3])

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [144]:
2*np.ones([2,2])

array([[2., 2.],
       [2., 2.]])

In [146]:
#Random Numbers
np.random.random([3,3])

array([[0.26098922, 0.96156649, 0.68900493],
       [0.12682481, 0.67545887, 0.28589629],
       [0.10673433, 0.37040125, 0.95049762]])

In [155]:
#Initialize Array[1 1 1 1 1 
                # 1 0 0 0 1
                # 1 0 9 0 1
                # 1 0 0 0 1
                # 1 1 1 1 1]
                
final = np.ones([5,5])                
final[1:4,1:4] = np.zeros([3,3])
final[2][2] = 9
print(final)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [158]:
a = [2,3,4]
np.cos(a)


TypeError: can only concatenate list (not "int") to list

In [161]:
a = np.array([2,3,4])
a=a+3
print(a)


[5 6 7]


In [162]:
np.cos(a)

array([0.28366219, 0.96017029, 0.75390225])

In [176]:
#Reshaping Arrays
a=np.array([[1,2,3],[5,6,7]])
print(a)
print('\n After Reshaping \n')
b=a.reshape(3,2)
print(b)

[[1 2 3]
 [5 6 7]]

 After Reshaping 

[[1 2]
 [3 5]
 [6 7]]


In [178]:
#stack arrays vertically 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c=np.vstack([a,b,a,b])
print(c)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [180]:
#stack arrays horizontally 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c=np.hstack([a,b,a,b])
print(c)

[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
